### ISSUE TITLE
No correct memory cleanup when using 'exit'

### ISSUE THREAD

**Issue by LaurensRietveld** [christopherobin/php-spidermonkey#1]
There is no correct memorty cleanup when using 'exit'.  This causes a segfault with this msg:
JS API usage error: 1 contexts left in runtime upon JS_DestroyRuntime.
JS engine warning: leaking GC root 'res->input' at 0x203be10
JS engine warning: 1 GC root remains after destroying the JSRuntime.
This root may point to freed memory. Objects reachable through it have
not been finalized.

Bug is also reported on pecl: http://pecl.php.net/bugs/bug.php?id=22838

Solution for me was to change the JS_DestroyRuntime call in PHP_RSHUTDOWN_FUNCTION (spidermonkey.c) to a JS_ShutDown call

**Comment by christopherobin** [comment]
JS_DestroyRuntime can be harmful in the case where one or more JS_Runtime do exists according to the documentation, I'm gonna research on how to fix the issue in more clean fashion.
In the meantime I'll work on making spidermonkey 1.8.5 work with the extension as gnome3 uses it; meaning that distros providing gnome3 will also provides spidermonkey 1.8.5 (which has several API breaking changes compared to 1.8.0).
