### ISSUE TITLE
Build fails on OS X

### ISSUE THREAD

**Issue by ryandesign** [christopherobin/php-spidermonkey#3]
Building the spidermonkey 1.0.0 PHP extension with spidermonkey 1.8.5-1.0.0 fails on OS X with the error:

```
ccache /usr/bin/gcc-4.2 ${wl}-undefined ${wl}dynamic_lookup -o .libs/spidermonkey.so -bundle  .libs/spidermonkey.o .libs/spidermonkey_context.o .libs/spidermonkey_external.o .libs/spidermonkey_streams.o  -L/opt/local/lib -l  -arch x86_64 -arch x86_64 -Wl,-rpath -Wl,/opt/local/lib
ld: library not found for -l-Wl,-rpath
```

This is because SPIDERMONKEY_LIBNAME doesn't get set. This is because config.m4 checks specifically for libraries whose names end with ".so". On OS X, the library extension is not ".so" but instead ".dylib".

**Comment by christopherobin** [comment]
Fixed by aurora
